# Generated by Django 5.2.11 on 2026-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='15 min después de creación. Solo aplica en estado pendiente.', null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='grupo_pago',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID que agrupa las reservas de una misma compra', null=True, verbose_name='Grupo de Pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('apartado', 'Apartado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
