# Generated by Django 5.2.11 on 2026-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_fecha_expiracion_reserva_grupo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_ticket',
            field=models.CharField(blank=True, help_text='Se genera automáticamente al confirmar la reserva.', max_length=8, null=True, unique=True, verbose_name='Código de Ticket'),
        ),
    ]
