# Generated by Django 5.2.11 on 2026-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_add_codigo_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula_asignado',
            field=models.CharField(blank=True, default='', help_text='Cédula de la persona a quien se asigna el asiento', max_length=20, verbose_name='Cédula del asignado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_menor_edad',
            field=models.BooleanField(default=False, verbose_name='¿Es menor de edad?'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_asignado',
            field=models.CharField(blank=True, default='', help_text='Nombre de la persona a quien se asigna el asiento', max_length=200, verbose_name='Nombre del asignado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='para_otra_persona',
            field=models.BooleanField(default=False, verbose_name='¿Asiento para otra persona?'),
        ),
    ]
