# Generated by Django 5.2.11 on 2026-04-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_cedula_asignado_reserva_es_menor_edad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
    ]
