# Generated by Django 5.2.11 on 2026-04-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_add_tipo_viaje_y_vuelta'),
        ('reservas', '0006_alter_reserva_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveIntegerField(verbose_name='Numero de Asiento')),
                ('piso_asiento', models.PositiveIntegerField(default=1, verbose_name='Piso del Asiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiracion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_asiento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_asiento', to='viajes.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Bloqueo de Asiento',
                'verbose_name_plural': 'Bloqueos de Asientos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('viaje', 'numero_asiento', 'piso_asiento')},
            },
        ),
    ]
