# Generated by Django 5.2.11 on 2026-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_bloqueoasiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueoasiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='bloqueoasiento',
            name='fecha_expiracion',
            field=models.DateTimeField(verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterField(
            model_name='bloqueoasiento',
            name='numero_asiento',
            field=models.PositiveIntegerField(verbose_name='Número de Asiento'),
        ),
    ]
