# Generated by Django 5.2.11 on 2026-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_bloqueoasiento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='viaja_con_animal',
            field=models.BooleanField(default=False, help_text='Si es verdadero, el pasajero debe presentar la tarjeta de vacunación del animal', verbose_name='¿Viaja con animal?'),
        ),
    ]
