# Generated by Django 5.2.11 on 2026-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_add_viaja_con_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='es_discapacitado',
            field=models.BooleanField(default=False, help_text='Indica si el pasajero de este asiento es una persona con discapacidad', verbose_name='¿Persona con discapacidad?'),
        ),
    ]
