# Generated by Django 5.2.11 on 2026-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_add_es_discapacitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='doc_cedula_representante',
            field=models.FileField(blank=True, help_text='Foto o escaneo de la cédula del representante legal', null=True, upload_to='documentos/menores/representantes/', verbose_name='Cédula del representante'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='doc_foto_menor',
            field=models.FileField(blank=True, help_text='Foto tipo carnet o selfie del menor', null=True, upload_to='documentos/menores/fotos/', verbose_name='Foto del menor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='doc_partida_nacimiento',
            field=models.FileField(blank=True, help_text='Documento de partida de nacimiento del menor (PDF o imagen)', null=True, upload_to='documentos/menores/partidas/', verbose_name='Partida de nacimiento'),
        ),
    ]
