# Generated by Django 5.2.11 on 2026-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_documentos_menor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='doc_vacunacion_animal',
            field=models.FileField(blank=True, help_text='Documento de vacunación del animal (PDF o imagen)', null=True, upload_to='documentos/animales/vacunacion/', verbose_name='Tarjeta de vacunación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_mascota',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('hamster', 'Hámster'), ('otro', 'Otro')], default='', help_text='Tipo de animal que viaja con el pasajero', max_length=20, verbose_name='Tipo de mascota'),
        ),
    ]
