# Generated by Django 5.2.11 on 2026-04-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_tipo_mascota_vacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='doc_discapacidad',
            field=models.FileField(blank=True, help_text='Certificado médico, RCP o documento que acredite la discapacidad (PDF o imagen)', null=True, upload_to='documentos/discapacidad/', verbose_name='Documento de discapacidad'),
        ),
    ]
