# Generated by Django 5.2.11 on 2026-07-03 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_doc_discapacidad'),
        ('viajes', '0013_rutaaerorutassnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'apartado', 'confirmado'])), fields=('viaje', 'numero_asiento', 'piso_asiento'), name='uniq_asiento_activo_por_viaje'),
        ),
    ]
