# Generated by Django 5.2.11 on 2026-07-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_reserva_uniq_asiento_activo_por_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='doc_permiso_viaje',
            field=models.FileField(blank=True, help_text='Autorización de viaje expedida por la autoridad competente (obligatoria cuando el menor no es hijo del comprador)', null=True, upload_to='documentos/menores/permisos/', verbose_name='Permiso de viaje del menor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='menor_no_es_hijo',
            field=models.BooleanField(default=False, help_text='Si es verdadero, se exige el permiso/autorización de viaje del menor', verbose_name='¿El menor no es hijo del comprador?'),
        ),
    ]
