# Generated by Django 5.2.11 on 2026-06-02 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionDebitoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_pago', models.UUIDField(blank=True, db_index=True, help_text='UUID de las reservas asociadas a este cobro.', null=True, verbose_name='Grupo de Pago')),
                ('banco', models.CharField(max_length=4, verbose_name='Código de Banco')),
                ('cedula', models.CharField(max_length=12, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=11, verbose_name='Teléfono')),
                ('nombre', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('concepto', models.CharField(blank=True, max_length=30, verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('otp_generado', 'OTP generado'), ('en_espera', 'En espera del receptor (AC00)'), ('aceptada', 'Aceptada (ACCP)'), ('rechazada', 'Rechazada'), ('error', 'Error de comunicación')], db_index=True, default='otp_generado', max_length=20, verbose_name='Estado')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Código del banco')),
                ('mensaje', models.CharField(blank=True, max_length=255, verbose_name='Mensaje del banco')),
                ('referencia', models.CharField(blank=True, max_length=30, verbose_name='Referencia')),
                ('operacion_id', models.CharField(blank=True, help_text='UUID devuelto por el banco; se usa para ConsultarOperaciones.', max_length=36, verbose_name='Id de operación (banco)')),
                ('otp_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta GenerarOtp')),
                ('debito_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta DebitoInmediato')),
                ('consulta_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta ConsultarOperaciones')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_debito_otp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Operación Débito OTP',
                'verbose_name_plural': 'Operaciones Débito OTP',
                'ordering': ['-creado'],
            },
        ),
    ]
