# Generated by Django 5.2.11 on 2026-07-02 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4conecta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operaciondebitootp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Operación Débito OTP', 'verbose_name_plural': 'Operaciones Débito OTP'},
        ),
        migrations.RemoveField(
            model_name='operaciondebitootp',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='operaciondebitootp',
            name='creado',
        ),
        migrations.AddField(
            model_name='operaciondebitootp',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/r4/%Y/%m/', verbose_name='Comprobante (opcional)'),
        ),
        migrations.AddField(
            model_name='operaciondebitootp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='operaciondebitootp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='banco',
            field=models.CharField(help_text='Código del banco (ej: 0192)', max_length=4),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='code',
            field=models.CharField(blank=True, help_text='Código de respuesta del banco', max_length=10),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='concepto',
            field=models.CharField(blank=True, default='Boletos Aerorutas', max_length=30),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='consulta_response',
            field=models.JSONField(blank=True, help_text='Respuesta cruda de ConsultarOperaciones', null=True),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='debito_response',
            field=models.JSONField(blank=True, help_text='Respuesta cruda de DebitoInmediato', null=True),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='estado',
            field=models.CharField(choices=[('otp_generado', 'OTP Generado'), ('en_espera', 'En Espera (AC00)'), ('aceptada', 'Aceptada (ACCP)'), ('rechazada', 'Rechazada'), ('error', 'Error')], default='otp_generado', max_length=20),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='grupo_pago',
            field=models.UUIDField(db_index=True, help_text='UUID del grupo de reserva'),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Mensaje de respuesta del banco'),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto en bolívares', max_digits=10),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='operacion_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de operación del banco', max_length=50),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='otp_response',
            field=models.JSONField(blank=True, help_text='Respuesta cruda de GenerarOtp', null=True),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia de la transacción', max_length=100),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
