# Generated by Django 5.2.11 on 2026-06-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4conecta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciondebitootp',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/r4/%Y/%m/', verbose_name='Comprobante (opcional)'),
        ),
    ]
