# Generated by Django 5.2.11 on 2026-07-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4conecta', '0002_alter_operaciondebitootp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='estado',
            field=models.CharField(choices=[('otp_generado', 'OTP Generado'), ('procesando', 'Procesando (débito en curso)'), ('en_espera', 'En Espera (AC00)'), ('aceptada', 'Aceptada (ACCP)'), ('rechazada', 'Rechazada'), ('error', 'Error')], default='otp_generado', max_length=20),
        ),
    ]
