# Generated by Django 5.2.11 on 2026-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r4conecta', '0003_alter_operaciondebitootp_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciondebitootp',
            name='concepto',
            field=models.CharField(blank=True, default='pago', max_length=30),
        ),
    ]
