# Generated by Django 5.2.11 on 2026-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Verificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Código'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
    ]
