# Generated by Django 5.2.11 on 2026-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_vip',
            field=models.BooleanField(default=False, help_text='Marca al usuario como pasajero VIP', verbose_name='¿Es VIP?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notas_admin',
            field=models.TextField(blank=True, default='', verbose_name='Notas del administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='servicio_vip',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino')], default='ninguno', max_length=10, verbose_name='Nivel VIP'),
        ),
    ]
