# Generated by Django 5.2.11 on 2026-03-12 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Identificador')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('pisos', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Pisos')),
            ],
            options={
                'verbose_name': 'Autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_vendedor', models.CharField(help_text='Número en formato internacional, ej: 584121234567', max_length=20, verbose_name='WhatsApp del Vendedor')),
                ('mensaje_whatsapp', models.TextField(default='Hola, quiero confirmar mi reserva de autobús:\n\n{detalles}', help_text='Usa {detalles} donde quieras insertar la info de la reserva', verbose_name='Plantilla de Mensaje WhatsApp')),
                ('nombre_empresa', models.CharField(default='VA-Bus', max_length=200, verbose_name='Nombre de la Empresa')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Tasa BCV (Bs/$)')),
                ('tasa_actualizada', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización de Tasa')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('duracion_estimada', models.CharField(blank=True, max_length=50, verbose_name='Duración Estimada')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'unique_together': {('origen', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='viajes.autobus', verbose_name='Autobús')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='viajes.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['fecha_salida', 'hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='PisoAutobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piso', models.PositiveIntegerField(default=1, verbose_name='Número de Piso')),
                ('filas', models.PositiveIntegerField(default=10, verbose_name='Cantidad de Filas')),
                ('asientos_izquierda', models.PositiveIntegerField(default=2, verbose_name='Asientos Lado Izquierdo (por fila)')),
                ('asientos_derecha', models.PositiveIntegerField(default=2, verbose_name='Asientos Lado Derecho (por fila)')),
                ('asientos_fondo', models.PositiveIntegerField(default=0, verbose_name='Asientos en el Fondo (fila extra)')),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos_config', to='viajes.autobus', verbose_name='Autobús')),
            ],
            options={
                'verbose_name': 'Piso de Autobús',
                'verbose_name_plural': 'Pisos de Autobús',
                'ordering': ['numero_piso'],
                'unique_together': {('autobus', 'numero_piso')},
            },
        ),
    ]
