# Generated by Django 5.2.11 on 2026-03-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisoautobus',
            name='tiene_puerta_trasera',
            field=models.BooleanField(default=False, help_text='Si está activo, no se generan asientos en el fondo (zona de puerta)', verbose_name='¿Tiene puerta trasera?'),
        ),
    ]
