# Generated by Django 5.2.11 on 2026-03-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_pisoautobus_tiene_puerta_trasera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisoautobus',
            name='puerta_lateral_fila_fin',
            field=models.PositiveIntegerField(default=0, help_text='Última fila afectada por la puerta lateral (1-indexada)', verbose_name='Puerta lateral - Fila fin'),
        ),
        migrations.AddField(
            model_name='pisoautobus',
            name='puerta_lateral_fila_inicio',
            field=models.PositiveIntegerField(default=0, help_text='Primera fila afectada por la puerta lateral (1-indexada)', verbose_name='Puerta lateral - Fila inicio'),
        ),
        migrations.AddField(
            model_name='pisoautobus',
            name='puerta_lateral_lado',
            field=models.CharField(choices=[('ninguno', 'Sin puerta lateral'), ('derecha', 'Puerta lado derecho'), ('izquierda', 'Puerta lado izquierdo')], default='ninguno', help_text='Lado del bus donde está la puerta lateral (elimina asientos de ese lado en las filas indicadas)', max_length=10, verbose_name='Puerta lateral'),
        ),
        migrations.AlterField(
            model_name='pisoautobus',
            name='tiene_puerta_trasera',
            field=models.BooleanField(default=False, help_text='Si está activo, no se generan asientos en el fondo', verbose_name='¿Tiene puerta trasera (fondo)?'),
        ),
    ]
