# Generated by Django 5.2.11 on 2026-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_pisoautobus_puerta_lateral_fila_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pisoautobus',
            name='asientos_derecha',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='asientos_fondo',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='asientos_izquierda',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='puerta_lateral_fila_fin',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='puerta_lateral_fila_inicio',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='puerta_lateral_lado',
        ),
        migrations.RemoveField(
            model_name='pisoautobus',
            name='tiene_puerta_trasera',
        ),
        migrations.AddField(
            model_name='pisoautobus',
            name='columnas',
            field=models.PositiveIntegerField(default=5, verbose_name='Columnas de la Grilla'),
        ),
        migrations.AddField(
            model_name='pisoautobus',
            name='layout',
            field=models.JSONField(blank=True, default=list, help_text='Grilla 2D: cada celda tiene type (seat/door/empty/aisle/stairs) y number (para asientos)', verbose_name='Layout de Asientos'),
        ),
        migrations.AlterField(
            model_name='pisoautobus',
            name='filas',
            field=models.PositiveIntegerField(default=10, verbose_name='Filas de la Grilla'),
        ),
    ]
