# Generated by Django 5.2.11 on 2026-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_remove_pisoautobus_asientos_derecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobus',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='propietario',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='domicilio_fiscal',
            field=models.TextField(blank=True, default='', verbose_name='Domicilio Fiscal'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='lema',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lema de la Empresa'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='rif',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RIF'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tipo_cuenta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='nombre_empresa',
            field=models.CharField(default='Aerorutas de Venezuela', max_length=200, verbose_name='Nombre de la Empresa'),
        ),
    ]
