# Generated by Django 5.2.11 on 2026-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_autobus_anio_autobus_color_autobus_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_fin_venta',
            field=models.DateField(blank=True, help_text='Fecha límite para reservar. Dejar vacío = abierto hasta la salida.', null=True, verbose_name='Cierre de Venta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_inicio_venta',
            field=models.DateField(blank=True, help_text='Fecha desde la cual el viaje es visible para reservar. Dejar vacío = siempre visible.', null=True, verbose_name='Inicio de Venta'),
        ),
    ]
