# Generated by Django 5.2.11 on 2026-03-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_add_fecha_venta_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_fin_venta',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_inicio_venta',
        ),
        migrations.CreateModel(
            name='ProgramacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días: 0=Lunes, 1=Martes, ..., 6=Domingo. Vacío = todos los días.', verbose_name='Días de la Semana')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='viajes.autobus', verbose_name='Autobús')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='viajes.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Programación de Viaje',
                'verbose_name_plural': 'Programaciones de Viaje',
                'ordering': ['fecha_inicio', 'hora_salida'],
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='programacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='viajes.programacionviaje', verbose_name='Programación'),
        ),
    ]
