# Generated by Django 5.2.11 on 2026-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_add_programacion_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='programacion',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_fin_venta',
            field=models.DateField(blank=True, help_text='Hasta cuándo se pueden reservar puestos. Vacío = abierto hasta la salida.', null=True, verbose_name='Cierre de Venta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_inicio_venta',
            field=models.DateField(blank=True, help_text='Desde cuándo se pueden reservar puestos. Vacío = ya disponible.', null=True, verbose_name='Inicio de Venta'),
        ),
        migrations.DeleteModel(
            name='ProgramacionViaje',
        ),
    ]
