# Generated by Django 5.2.11 on 2026-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_revert_to_simple_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_vuelta',
            field=models.DateField(blank=True, help_text='Solo aplica para viajes de Ida y Vuelta.', null=True, verbose_name='Fecha de Vuelta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_vuelta',
            field=models.TimeField(blank=True, help_text='Solo aplica para viajes de Ida y Vuelta.', null=True, verbose_name='Hora de Vuelta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('ida', 'Solo Ida'), ('ida_vuelta', 'Ida y Vuelta')], default='ida', max_length=15, verbose_name='Tipo de Viaje'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_fin_venta',
            field=models.DateField(blank=True, help_text='Fecha límite para comprar puestos. Vacío = abierto hasta la salida.', null=True, verbose_name='Expiración de Compra'),
        ),
    ]
