# Generated by Django 5.2.11 on 2026-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_add_tipo_viaje_y_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobus',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Desmarcar si el autobús no está operativo.', verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='motivo_no_disponible',
            field=models.CharField(blank=True, default='', help_text='Ej: En mantenimiento, avería mecánica, revisión técnica, etc.', max_length=300, verbose_name='Motivo de no disponibilidad'),
        ),
    ]
