# Generated by Django 5.2.11 on 2026-05-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0010_bus_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codofi', models.CharField(help_text="Código numérico único de la oficina. Ej: '01', '04', '100'", max_length=10, unique=True, verbose_name='Código (codofi)')),
                ('desofi', models.CharField(help_text="Nombre completo. Ej: 'CARACAS LA BANDERA'", max_length=100, verbose_name='Nombre (desofi)')),
                ('siglas', models.CharField(blank=True, default='', help_text="Siglas cortas. Ej: 'CCS', 'MBO', 'MRD'", max_length=10, verbose_name='Siglas')),
                ('estado', models.CharField(blank=True, default='', help_text="Estado venezolano. Ej: 'Distrito Capital', 'Zulia'", max_length=50, verbose_name='Estado')),
                ('ciudad', models.CharField(blank=True, default='', help_text='Ciudad donde está ubicada (para el mapa). Si está vacío se infiere de desofi.', max_length=100, verbose_name='Ciudad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitud')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['desofi'],
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='oficina_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_como_destino', to='viajes.oficina', verbose_name='Oficina destino'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='oficina_origen',
            field=models.ForeignKey(blank=True, help_text='Opcional. Vincula la ruta a una oficina existente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_como_origen', to='viajes.oficina', verbose_name='Oficina origen'),
        ),
    ]
