# Generated by Django 5.2.11 on 2026-05-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0011_oficina_ruta_oficina_destino_ruta_oficina_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='oficina_destino',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='oficina_origen',
        ),
    ]
