# Generated by Django 5.2.11 on 2026-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0012_remove_ruta_oficina_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAerorutasSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('data', models.JSONField(blank=True, default=list, help_text='Lista de viajes ya transformados al formato de la app.', verbose_name='Viajes (JSON)')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última precarga')),
            ],
            options={
                'verbose_name': 'Catálogo Aerorutas (por fecha)',
                'verbose_name_plural': 'Catálogo Aerorutas (por fecha)',
                'ordering': ['fecha'],
            },
        ),
    ]
