# Generated by Django 5.2.11 on 2026-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0013_rutaaerorutassnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='aerorutas_codrut',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Aerorutas: código de ruta (codrut)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='aerorutas_ofides',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Aerorutas: oficina de destino (ofides)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='aerorutas_ofisal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Aerorutas: oficina de salida (ofisal)'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(condition=models.Q(('aerorutas_codrut', ''), _negated=True), fields=('aerorutas_codrut', 'aerorutas_ofisal', 'aerorutas_ofides', 'fecha_salida'), name='uniq_viaje_espejo_aerorutas'),
        ),
    ]
