# Generated by Django 5.2.11 on 2026-03-13 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Método')),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares'), ('USD', 'Dólares')], default='BS', help_text='Determina si el monto se muestra en Bs o USD', max_length=3, verbose_name='Moneda')),
                ('descripcion', models.CharField(blank=True, help_text="Ej: 'Se acredita más rápido'. Aparece como badge debajo del nombre.", max_length=200, verbose_name='Badge / Descripción corta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DatoMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(help_text="Ej: 'Banco', 'RIF', 'Teléfono', 'Email'", max_length=100, verbose_name='Etiqueta')),
                ('valor', models.CharField(help_text="Ej: 'Banco Nacional de Crédito', 'J-313189260'", max_length=300, verbose_name='Valor')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='pagos.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Dato del Método',
                'verbose_name_plural': 'Datos del Método',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grupo_pago', models.UUIDField(db_index=True, help_text='UUID que agrupa las reservas de una misma compra', verbose_name='Grupo de Pago')),
                ('numero_referencia', models.CharField(blank=True, help_text='Opcional pero recomendado', max_length=100, verbose_name='Número de Referencia / Comprobante')),
                ('imagen', models.ImageField(upload_to='comprobantes/%Y/%m/', verbose_name='Captura del Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('moneda', models.CharField(default='BS', max_length=3, verbose_name='Moneda del monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('nota_admin', models.TextField(blank=True, help_text='Motivo de rechazo u observaciones', verbose_name='Nota del administrador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='pagos.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
