# Generated by Django 5.2.11 on 2026-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='foto_billete',
            field=models.ImageField(blank=True, help_text='Requerida cuando el pago es en divisas/efectivo', null=True, upload_to='comprobantes/billetes/%Y/%m/', verbose_name='Foto del billete'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='requiere_foto_billete',
            field=models.BooleanField(default=False, help_text='Si es pago en divisas/efectivo, el cliente debe subir foto del billete', verbose_name='¿Requiere foto del billete?'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('divisas', 'Divisas (Efectivo)'), ('zinli', 'Zinli'), ('zelle', 'Zelle'), ('binance', 'Binance'), ('otro', 'Otro')], default='transferencia', help_text='Categoría del método de pago', max_length=20, verbose_name='Tipo de método'),
        ),
    ]
