# Generated by Django 5.2.11 on 2026-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_comprobantepago_foto_billete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('divisas', 'Divisas (Efectivo)'), ('zinli', 'Zinli'), ('zelle', 'Zelle'), ('binance', 'Binance'), ('cobro_inmediato', 'Cobro Inmediato (Débito OTP)'), ('otro', 'Otro')], default='transferencia', help_text='Categoría del método de pago', max_length=20, verbose_name='Tipo de método'),
        ),
    ]
