# Generated by Django 5.2.11 on 2026-08-07 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_crear_metodo_cobro_inmediato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='disponible_caja',
            field=models.BooleanField(default=False, help_text='La cajera puede cobrar con este método en el módulo de Caja.', verbose_name='Disponible en caja (taquilla)'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='disponible_web',
            field=models.BooleanField(default=True, help_text='Se le muestra al cliente cuando paga desde la web o la app.', verbose_name='Disponible en web/app'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('divisas', 'Divisas (Efectivo)'), ('efectivo', 'Efectivo'), ('debito', 'Débito (punto de venta)'), ('cashea', 'Cashea'), ('zinli', 'Zinli'), ('zelle', 'Zelle'), ('binance', 'Binance'), ('cobro_inmediato', 'Cobro Inmediato (Débito OTP)'), ('otro', 'Otro')], default='transferencia', help_text='Categoría del método de pago', max_length=20, verbose_name='Tipo de método'),
        ),
        migrations.CreateModel(
            name='PagoCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grupo_pago', models.UUIDField(db_index=True, help_text='UUID que agrupa las reservas vendidas en esta operación', verbose_name='Grupo de Pago')),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares'), ('USD', 'Dólares')], default='BS', max_length=3, verbose_name='Moneda cobrada')),
                ('monto', models.DecimalField(decimal_places=2, help_text='En la moneda indicada arriba', max_digits=14, verbose_name='Monto cobrado')),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Precio de los boletos; referencia para el arqueo', max_digits=12, verbose_name='Equivalente en USD')),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa con la que se calculó el monto en bolívares', max_digits=12, null=True, verbose_name='Tasa BCV usada')),
                ('referencia', models.CharField(blank=True, help_text='Nº de referencia del pago móvil/débito, o código de Cashea', max_length=100, verbose_name='Referencia')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('cliente_cedula', models.CharField(blank=True, max_length=20, verbose_name='Cédula del cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('nota', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero/a')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_caja', to='pagos.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Venta en Caja',
                'verbose_name_plural': 'Ventas en Caja',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
